#!/bin/bash
# The function was taken from : http://unix.stackexchange.com/questions/2881/show-a-notification-across-all-running-x-displays/230062#230062
# Credit : Josef Kufner : http://unix.stackexchange.com/users/93227/josef-kufner
# Author : Shatadru Bandyopadhyay 
function nott() {
/bin/grep -sozZe '^DBUS_SESSION_BUS_ADDRESS=[a-zA-Z0-9:=,/-]*$' /proc/*/environ \
| /usr/bin/php -r '
        $busses = array();
        array_shift($argv);
        while($ln = fgets(STDIN)) {
                list($f, $env) = explode("\0", $ln, 2);
                if (file_exists($f)) {
                        $user = fileowner($f);
                        $busses[$user][trim($env)] = true;
                }
        }
        foreach ($busses as $user => $user_busses) {
                foreach ($user_busses as $env => $true) {
                        if (pcntl_fork()) {
                                posix_seteuid($user);
                                $env_array = array("DBUS_SESSION_BUS_ADDRESS" => preg_replace("/^DBUS_SESSION_BUS_ADDRESS=/", "", $env));
                                pcntl_exec("/usr/bin/notify-send", $argv, $env_array);
                        }
                }
        }
' -- "$@"
}
NOW=$(date +"%e %b %Y, %a %r")
USER=`whoami`



if [ -z $1 ]
then
        echo "not set"
        logger "$NOW : Local User: $USER logged in"
        echo   "$NOW : Local User: $USER logged in "  >> /var/log/sshlogin
else
        echo "set"
        IP=$1
        nott "Remote Login from $IP as USER: $USER at $NOW"
        logger  "$NOW : Remote Login from $IP as USER: $USER"
        echo    "$NOW : Remote Login from $IP as USER: $USER" >> /var/log/sshlogin
fi
