# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Add execute permission
      run: chmod +x otpgen/otpgen.sh

    - name: test_1 Print version
      run: bash ./otpgen/otpgen.sh -V

    - name: test_2_1 Install packages
      run: sudo apt-get install zbar-tools xclip oathtool

    - name: test_2_2 Test install command from normal user with sudo
      run: sudo bash -x ./otpgen/otpgen.sh -i

    - name: test_2_3 remove installation dir for next run 
      run:  sudo rm -rf ~/otpgen

    #- name: test_2_4 Test install command from normal user without sudo
    #  run: bash -x ./otpgen/otpgen.sh -i

    - name: Testing clean install command with sudo
      run: echo y| sudo bash -x ./otpgen/otpgen.sh --clean-install


   ## TODO: test add key, list_key, gen_key (both HOTP, TOTP)
